### PR TITLE
:bug: Fixed indexed_builder and handler_builder tests

### PR DESCRIPTION
**Pull request by AshleyRoll**
The two tests utilised exactly the name message, field and other types resulting in an ODR violations causing the code to incorrectly call the wrong callback (other file).

Fixed by placing each instance in an anonymous namespace to prevent them leaving the translation unit.

### CODE REVIEW

**Comment by AshleyRoll** [comment]
Hi Luke, I wanted to experiment with a different `bitset` but found the test was broken so I fixed it first :)

**Comment by elbeno** [comment]
Oh hi Ashley, actually Luke and I worked this yesterday and we have an updated working branch already too...

**Comment by AshleyRoll** [comment]
Haha, fair enough 😃. Was blocking me so I quickly fixed it. Just close the PR if you don't need the fix.

**Comment by bdeane-intel** [comment]
Thanks for the confirmation - I found the ODR issue last night and fixed the same way! The existing PR should be passing now I think.

**Comment by bdeane-intel** [comment]
OK, closing this one since the original PR is now merged, but thanks, Ashley!

**Pull request closed without merging**
