### PR TITLE
Add raw storage definition to support uin8_t based messages

### PR DESCRIPTION
**Pull request by Thurnheer**
Would be an addition to  #446, #315 and #448

### CODE REVIEW

**Comment by elbeno** [comment]
It's already trivial to create 8-bit storage as seen at https://github.com/intel/compile-time-init-build/blob/main/test/msg/message.cpp#L350 - I'm not sure what this adds?

Also a couple of notes:
- `raw_storage_t` isn't a good name: all storage is "raw".
- `raw_view` and `raw_owning` aren't good names: it's not raw on the outside, everything is still typed.

Honestly, I think what we have is all that's needed - a single storage definition on the outside (which only needs one definition and can then be used with any kind of message, owning or view) and a single using for the message type. Adding this extra stuff doesn't improve that?

**Comment by Thurnheer** [comment]
Thank you for your honest reply and for your time reviewing my PR.

I'll probably not fully get your solution. I will try on Monday. 

Thanks for the fast reply, and I wish you a nice weekend.

**Comment by elbeno** [comment]
Thanks for the issue and the PR! I hope we can get to a good solution here because the use case of `uint8_t` for storage is clearly an important one.

I did notice looking through the (existing) code that the types seem to be a little coupled to stdx::span and std::array right now, maybe I could improve that...

**Comment by lukevalenty** [comment]
Hi @Thurnheer, @elbeno made a PR that adds a test with `uint8_t` backed storage. Take a look at how he creates a message with owning storage here: https://github.com/intel/compile-time-init-build/pull/448/files#diff-e2731b151a028a5dbf30f15cc8365556236a62f752824ada09a55864c8c73061R350

**Pull request closed without merging**
