### PR TITLE
:art: Refactor nexus demux algorithm

### PR DESCRIPTION
**Pull request by elbeno**
Demux is a tuple-based version of sort followed chunk_by.

### CODE REVIEW

**Comment by lukevalenty** [comment]
Have you checked compilation times for the compilation performance test?

**Comment by elbeno** [comment]
Yes, the big nexus benchmark is about 0.5s more on my laptop. But then some months ago it was about 6s more.

**Comment by elbeno** [comment]
Looking back, it looks like #323 actually impacted the benchmark times quite a bit. Maybe we can take a look at how to bring that in a bit.

**Comment by elbeno** [comment]
#346 should restore compilation perf.

**Review by lukevalenty — APPROVED** [review]
*chef's kiss*

**Pull request merged**
